# Generated by Django 3.0.4 on 2020-05-13 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharaapp', '0002_auto_20200513_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=5000, null=True)),
                ('links', models.CharField(blank=True, max_length=5000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('upvote', models.PositiveIntegerField()),
                ('downvote', models.PositiveIntegerField()),
                ('totalscore', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
