# Generated by Django 3.0.4 on 2020-05-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharaapp', '0003_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='file',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
